services:
  nginx:
    container_name: repo-tracker-nginx
    restart: always
    build:
      context: ./apps/nginx
    ports:
      - "80:80"
    networks:
      - app-net

  postgres:
    container_name: repo-tracker-db
    restart: always
    image: postgres:16-alpine
    env_file:
      - .env.postgres
    volumes:
      - repo-tracker-postgres-data:/var/lib/postgresql/data
    networks:
      - data-net

  redis:
    container_name: repo-tracker-redis
    restart: always
    image: redis/redis-stack-server:latest
    volumes:
      - repo-tracker-redis-data:/data
    networks:
      - data-net

  api:
    container_name: repo-tracker-api
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        PACKAGE_NAME: api
    networks:
      - app-net
      - data-net

  web:
    container_name: repo-tracker-web
    restart: always
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        PACKAGE_NAME: web
        NEXT_PUBLIC_API_URL: "/api"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
  data-net:
    driver: bridge

volumes:
  repo-tracker-postgres-data:
  repo-tracker-redis-data: